//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐA1_Chia_se_anh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int MaA { get; set; }
        public Nullable<int> MaNS { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaAB { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual AlBum AlBum { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        public virtual NgheSi NgheSi { get; set; }
    }
}
