//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐA1_Chia_se_anh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int MaBaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public Nullable<int> MaND { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public byte[] AnhBaiViet { get; set; }
        public string NoiDung { get; set; }
    
        public virtual CTNguoiDung CTNguoiDung { get; set; }
    }
}
