//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐA1_Chia_se_anh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgheSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NgheSi()
        {
            this.Anhs = new HashSet<Anh>();
        }
    
        public int MaNS { get; set; }
        public string TenNS { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> SĐT { get; set; }
        public string Email { get; set; }
        public string AnhNS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh> Anhs { get; set; }
        public virtual CTNguoiDung CTNguoiDung { get; set; }
    }
}
